# Employee Performance Prediction – Basic ML Workflow

Objective:
Predict whether an employee's performance is High or Low using basic machine learning steps.

In [69]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error
from xgboost import XGBRegressor
import joblib

In [70]:
import pandas as pd

# Load dataset
df = pd.read_csv(r"C:\Users\Priyal Kantharia\Desktop\ALL projects\Employee performance Analysis\data\Extended_Employee_Performance_and_Productivity_Data.csv")



# Display first few rows
df.head()

,Employee_ID,Department,Gender,Age,Job_Title,Hire_Date,Years_At_Company,Education_Level,Unnamed: 8,Monthly_Salary,Work_Hours_Per_Week,Projects_Handled,Overtime_Hours,Sick_Days,Remote_Work_Frequency,Team_Size,Training_Hours,Promotions,Employee_Satisfaction_Score,Resigned
0,1,IT,Male,55,Specialist,03:05.6,2,High School,NaN,6750,33,32,22,2,0,14,66,0,2.63,False
1,2,Finance,Male,29,Developer,03:05.6,0,High School,NaN,7500,34,34,13,14,100,12,61,2,1.72,False
2,3,Finance,Male,55,Specialist,03:05.6,8,High School,NaN,5850,37,27,6,3,50,10,1,0,3.17,False
3,4,Customer Support,Female,48,Analyst,03:05.6,7,Bachelor,NaN,4800,52,10,28,12,100,10,0,1,1.86,False
4,5,Engineering,Female,36,Analyst,03:05.6,3,Bachelor,NaN,4800,38,11,29,13,100,15,9,1,1.25,False

In [71]:
df.shape  # Rows and columns
df.columns  # List of columns
df.info()  # Data types and missing values
df.describe()  # Statistical summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Employee_ID                  100000 non-null  int64
 1   Department                   100000 non-null  object
 2   Gender                       100000 non-null  object
 3   Age                          100000 non-null  int64
 4   Job_Title                    100000 non-null  object
 5   Hire_Date                    100000 non-null  object
 6   Years_At_Company             100000 non-null  int64
 7   Education_Level              100000 non-null  object
 8   Unnamed: 8                   0 non-null       float64
 9   Monthly_Salary               100000 non-null  int64
 10  Work_Hours_Per_Week          100000 non-null  int64
 11  Projects_Handled             100000 non-null  int64
 12  Overtime_Hours               100000 non-null  int64
 13  Sick_Days                    100000 non-null  int64
 14  Remote_Work_Frequency        100000 non-null  int64
 15  Team_Size                    100000 non-null  int64
 16  Training_Hours               100000 non-null  int64
 17  Promotions                   100000 non-null  int64
 18  Employee_Satisfaction_Score  100000 non-null  float64
 19  Resigned                     100000 non-null  bool
dtypes: bool(1), float64(2), int64(12), object(5)
memory usage: 14.6+ MB

,Employee_ID,Age,Years_At_Company,Unnamed: 8,Monthly_Salary,Work_Hours_Per_Week,Projects_Handled,Overtime_Hours,Sick_Days,Remote_Work_Frequency,Team_Size,Training_Hours,Promotions,Employee_Satisfaction_Score
count,100000.000000,100000.000000,100000.000000,0.0,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,41.029410,4.476070,NaN,6403.211000,44.956950,24.431170,14.514930,7.008550,50.090500,10.013560,49.506060,0.999720,2.999088
std,28867.657797,11.244121,2.869336,NaN,1372.508717,8.942003,14.469584,8.664026,4.331591,35.351157,5.495405,28.890383,0.815872,1.150719
min,1.000000,22.000000,0.000000,NaN,3850.000000,30.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
25%,25000.750000,31.000000,2.000000,NaN,5250.000000,37.000000,12.000000,7.000000,3.000000,25.000000,5.000000,25.000000,0.000000,2.010000
50%,50000.500000,41.000000,4.000000,NaN,6500.000000,45.000000,24.000000,15.000000,7.000000,50.000000,10.000000,49.000000,1.000000,3.000000
75%,75000.250000,51.000000,7.000000,NaN,7500.000000,53.000000,37.000000,22.000000,11.000000,75.000000,15.000000,75.000000,2.000000,3.990000
max,100000.000000,60.000000,10.000000,NaN,9000.000000,60.000000,49.000000,29.000000,14.000000,100.000000,19.000000,99.000000,2.000000,5.000000

## Data Preprocessing
Cleaning data and converting categorical features into numerical format.

In [72]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [73]:
y = df["Performance_Score"]
X = df.drop("Performance_Score", axis=1)

KeyError: 'Performance_Score'

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
numeric_features = X.select_dtypes(include=['int64','float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [ ]:
pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBRegressor(random_state=42))
])

In [ ]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['Employee_ID', 'Age', 'Years_At_Company', 'Monthly_Salary',
       'Work_Hours_Per_Week', 'Projects_Handled', 'Overtime_Hours',
       'Sick_Days', 'Remote_Work_Frequency', 'Team_Size', 'Training_Hours',
       'Promotions', 'Employee_Satisfaction_Score'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEn...
                              feature_types=None, gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, random_state=42, ...))])

In [ ]:
y_pred = pipeline.predict(X_test)

print("R2:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

R2: 1.0
MAE: 1.951257288455963e-05

In [ ]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(pipeline, X, y, cv=5, scoring="r2")

print("CV R2 Mean:", cv_scores.mean())
print("CV R2 Std:", cv_scores.std())

CV R2 Mean: 1.0
CV R2 Std: 0.0

In [ ]:
joblib.dump(pipeline, "employee_model.pkl")

['employee_model.pkl']

In [ ]:
import streamlit as st
import pandas as pd
import joblib

st.title("Employee Performance Prediction System")

@st.cache_resource
def load_model():
    return joblib.load("employee_model.pkl")

model = load_model()

uploaded_file = st.file_uploader("Upload Employee CSV", type=["csv"])

if uploaded_file:
    data = pd.read_csv(uploaded_file)

    predictions = model.predict(data)

    data["Predicted_Performance"] = predictions

    st.dataframe(data)

2026-02-25 15:57:01.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-25 15:57:01.542 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-25 15:57:01.546 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-25 15:57:01.548 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-25 15:57:01.549 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-25 15:57:01.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-25 15:57:01.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
joblib.dump(pipeline, "employee_model.pkl")

['employee_model.pkl']

In [ ]:
import sklearn
print(sklearn.__version__)

1.5.2